Project/views/items.py
from flask import Blueprint, request, flash, render_template, redirect, url_for
from werkzeug.datastructures import MultiDict
from sql.db import DB
from flask_login import login_required, current_user
import traceback as tb
shop = Blueprint('shop', __name__, url_prefix='/',template_folder='templates')

@shop.route("/shop", methods=["GET","POST"])
def shop_list():
    # UCID: ap2823
    # Date: 12/17/2022
    # Method to view all items as a logged-in user
    rows = []
    query = """SELECT id, name, description, stock, unit_price, image
               FROM IS601_S_Items WHERE visibility = 1"""
    args = [] # <--- append values to replace %s placeholders
    allowed_columns = ["name", "description", "unit_price"]
    for filter in allowed_columns[:-1]:
        if request.args.get(filter):
            query += f" and {filter} like %s"
            args.append(f"%{request.args.get(filter)}%")
    if request.args.get("order") and request.args.get("column"):
        if request.args.get("column") in allowed_columns \
            and request.args.get("order") in ["asc", "desc"]:
            query += f" ORDER BY {request.args.get('column')} {request.args.get('order')}"
    query += f" LIMIT %s"
    ql = int(request.args.get('limit', 25))
    if ql < 1 or ql > 100:
        flash("limit value should be in the range of 1-100; Defaulting to 25")
        args.append(25)
    else:
        args.append(ql)
    print("query",query)
    print("args", args)
    try:
        result = DB.selectAll(query, *args)
        if result.status and result.rows:
            rows = result.rows
    except Exception as e:
        print(tb.format_exc())
        flash("There was a problem loading items", "danger")
    return render_template("shop.html", rows=rows, allowed_columns=allowed_columns)

@shop.route("/shop/item", methods=["GET","POST"])
def shop_item():
    # UCID: ap2823
    # Date: 12/17/2022
    # Method to view an item as a logged-in user
    try:
        id = request.form.get("id") or request.args.get("id") or None
        result = DB.selectOne("SELECT id, name, description, stock, unit_price, image FROM IS601_S_Items WHERE id = %s", id)
        if result.status and result.row:
            rows = result.row
    except Exception as e:
        print("Error fetching item", e)
        flash("Item not found", "danger")
        rows = []
    return render_template("view_item.html", rows=rows if rows else {})

@shop.route("/cart", methods=["GET","POST"])
@login_required
def cart():
    # UCID: ap2823
    # Date: 12/17/2022
    # Method to add item to a cart as a logged-in user
    item_id = request.form.get("item_id")
    id = request.form.get("id", item_id)
    print("id", id)
    quantity = request.form.get("quantity", 1, type=int)
    user_id = current_user.get_id()
    if id and user_id:
        if quantity > 0:
            try:
                result = DB.selectOne("SELECT unit_price,name,stock from IS601_S_Items WHERE id = %s", id)
                print("result", result)
                if result.status and result.row:
                    unit_price = result.row["unit_price"]
                    name = result.row["name"]
                    stock = result.row["stock"]
                    if quantity > stock:
                        flash(f"{quantity} {name}s are not available; Please reduce the quantity", "danger")
                    else:
                        if item_id: # update from cart
                            result = DB.insertOne("""
                            UPDATE IS601_S_Cart SET
                            quantity = %(quantity)s,
                            unit_price = %(unit_price)s
                            WHERE item_id = %(id)s and user_id = %(user_id)s
                            """,{
                                "id":id,
                                "quantity": quantity,
                                "unit_price":unit_price,
                                "user_id":user_id
                            })
                            if result.status:
                                flash(f"Updated quantity for {name} to {quantity}", "success")
                        else: #add from shop
                            result = DB.insertOne("""
                            INSERT INTO IS601_S_Cart (item_id, quantity, unit_price, user_id)
                            VALUES(%(id)s, %(quantity)s, %(unit_price)s, %(user_id)s)
                            ON DUPLICATE KEY UPDATE
                            quantity = quantity + %(quantity)s,
                            unit_price = %(unit_price)s
                            """,{
                                "id":id,
                                "quantity": quantity,
                                "unit_price":unit_price,
                                "user_id":user_id
                            })
                            if result.status:
                                flash(f"Added {quantity} of {name} to cart", "success")
            except Exception as e:
                print("Error updating cart" ,e)
                flash("Error updating cart", "danger")
        else:
            # assuming delete
            try:
                result = DB.delete("DELETE FROM IS601_S_Cart where item_id = %s and user_id = %s", id, user_id)
                if result.status:
                    flash("Deleted item from cart", "success")
            except Exception as e:
                print("Error deleting item", e)
                flash("Error deleting item from cart", "danger")
    rows = []
    try:
        result = DB.selectAll("""SELECT c.id, item_id, name, c.quantity, (c.quantity * c.unit_price) as subtotal 
        FROM IS601_S_Cart c JOIN IS601_S_Items i on c.item_id = i.id
        WHERE c.user_id = %s
        """, current_user.get_id())
        if result and result.rows:
            rows = result.rows
    except Exception as e:
        print("Error getting cart", e)
        flash("Error fetching cart", "danger")
    return render_template("cart.html", rows=rows)

@shop.route("/confirm_order", methods=["GET","POST"])
@login_required
def confirm_order():
    # UCID: ap2823
    # Date: 12/17/2022
    # Method to confirm order as a logged-in user
    cart = []
    total = 0
    try:
        # get cart to verify
        result = DB.selectAll("""SELECT c.id, item_id, name, c.quantity, i.stock, c.unit_price as cart_cost, i.unit_price as item_cost, (c.quantity * c.unit_price) as subtotal 
        FROM IS601_S_Cart c JOIN IS601_S_Items i on c.item_id = i.id
        WHERE c.user_id = %s
        """, current_user.get_id())
        if result.status and result.rows:
            cart = result.rows
        # verify cart
        has_error = False
        for item in cart:
            if item["quantity"] > item["stock"]:
                flash(f"Item {item['name']} doesn't have enough stock left", "warning")
                has_error = True
                if item["stock"] == 0:
                    result = DB.delete("DELETE FROM IS601_S_Cart where item_id = %s and user_id = %s", item["item_id"], current_user.get_id())
                    flash(f"Deleting item: {item['name']} from your cart", "warning")
                else:
                    result = DB.insertOne("""
                            UPDATE IS601_S_Cart SET
                            quantity = %(quantity)s,
                            WHERE item_id = %(id)s and user_id = %(user_id)s
                            """,{
                                "id":id,
                                "quantity": item["stock"],
                                "item_id":item["item_id"],
                                "user_id":item['user_id']
                            })
                    if result.status:
                        flash(f"Updated quantity for {item['name']} to {item['stock']}", "warning")
            if item["cart_cost"] != item["item_cost"]:
                flash(f"Item {item['name']}'s price has changed, please refresh cart", "warning")
                has_error = True
                result = DB.insertOne("""
                            UPDATE IS601_S_Cart SET
                            unit_price = %(cost)s,
                            WHERE item_id = %(id)s and user_id = %(user_id)s
                            """,{
                                "id":id,
                                "cost": item["item_cost"],
                                "item_id":item["item_id"],
                                "user_id":item['user_id']
                            })
                if result.status:
                    flash(f"Updated cost for {item['name']} to {item['item_cost']}")
            total += float(item["subtotal"] or 0) 
        if has_error:
            return redirect(url_for("shop.cart"))
    except Exception as e:
        print("Transaction exception", e)
        flash("Something went wrong", "danger")
        tb.print_exc()
        return redirect(url_for("shop.cart"))
    # TODO route to thank you / summary page
    # TODO add link from cart page to this route
    return render_template("pending_order.html", rows=cart, total=total)

@shop.route("/place_order", methods=["GET","POST"])
@login_required
def place_order():
    # UCID: ap2823
    # Date: 12/17/2022
    # Method to place the order and clear cart
    total = float(request.form.get('total', 0))
    total = f"{total:.2f}"
    money_received = float(request.form.get("money_received", 0))
    if money_received and f"{money_received:.2f}" == total:
        flash("Payment received, proceeding to place order", "success")
    elif money_received:
        flash("Received payment is not equal to the total cost, aborting order", "danger")
        flash("Any amount debited will be refunded in 3-4 business days", "warning")
        return redirect(url_for("shop.cart"))
    else:
        flash("Payment Failed, Please try again")
        return redirect(url_for("shop.cart"))
    cart = []
    total = 0
    quantity = 0

Project/templates/401.html
{% extends "layout.html" %}
{% block title %}403{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="h1">Unauthorized</div>
</div>
{% endblock %}

Project/templates/_table_helper.html
{% macro render_table(title,data, ignored = [], view =None, edit=None, delete=None) %}
<div class="container-fluid">
    <div class="h1">{{title}}</div>
<table class="table bg-dark text-light">
    <thead>
        {% if data and data|length > 0 %}
        <tr class="text-capitalize">
            {% for r in data[0] %}
                {% if r not in ignored %}
                <th>{{r}}</th>
                {% endif %}
            {% endfor %}
            {% if view or edit or delete %}
            <th>Actions</th>
            {% endif %}
        </tr>
        {%endif%}
    </thead>
    <tbody>
        {% for r in data %}
        <tr>
            {% for k,v in r.items() %}
            {% if k not in ignored %}
            <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:1px;">{{v}}</td>
            {% endif %}
            {% endfor %}
            {% if view or edit or delete %}
            <td>
                {% if view and r["id"] %}
                <a href="{{url_for(view)}}?id={{r['id']}}">View</a>
                {% endif %}
                {% if edit and r["id"] %}
                <form action="{{url_for(edit)}}?id={{r['id']}}" method="POST">
                    <input type="submit" value="edit" />
                </form>
                {% endif %}
                {% if delete and r["id"] %}
                <a href="{{url_for(delete)}}?id={{r['id']}}">Delete</a>
                {% endif %}
            </td>
            {% endif %}
        </tr>
        {% endfor %}
        {% if not data %}
        <tr>
            <td colspan="100%">No results</td>
        </tr>
        {% endif %}
    </tbody>
</table>
</div>
{% endmacro %}

Project/templates/admin_items.html
{% extends "layout.html" %}
{% block title %}Items{% endblock %}

<!-- content -->
{% block content %}
{% from "_table_helper.html" import render_table %}
{% set view = "admin.view_item" %}
{% set edit = "admin.item" %}
{% set delete = "admin.delete" %}
{{render_table("Items", rows, ["user_id"], view, edit, delete)}}
{% endblock %}

Project/templates/cart.html
{% extends "layout.html" %}
{% block title %}Cart{% endblock %}

<!-- content -->
{% block content %}
<div class="container-fluid">
    <div class="h4">Cart</div>
    <table class="table text-light bg-dark">
        <thread>
            <tr>
                <th>Item</th>
                <th>Quantity</th>
                <th>Subtotal</th>
                <th>Actions</th>
            </tr>
        </thread>
        <tbody>
            {% set ns = namespace(total=0) %}
            {% for row in rows %}
            <tr>
                <td>{{row["name"]}}</td>
                <td style="width:10em">
                    <form method="POST">
                        <div class="row">
                            <input type="hidden" name="item_id" value="{{row['item_id']}}" />
                            <div class="col">
                                <input type="number" class="form-control" name="quantity"
                                    value="{{row['quantity']}}" />
                            </div>
                            <div class="col d-grid">
                                <input type="submit" value="Update"
                                    class="btn btn-secondary btn-sm" />
                            </div>
                        </div>
                    </form>
                </td>
                <td>{{row['subtotal']}}</td>
                <td>
                    <a href="{{url_for('shop.shop_item')}}?id={{row['item_id']}}">View</a>
                    <form method="POST">
                        <input type="hidden" name="item_id" value="{{row['item_id']}}" />
                        <input type="hidden" name="quantity" value="-1" />
                        <input type="submit" value="x" class="btn btn-danger btn-sm" />
                    </form>
                </td>
                <td>
                    <!-- lazy delete using quantity < 0 logic -->
                    
                </td>
                {# https://stackoverflow.com/a/51880609 #}
                {% set ns.total = ns.total + row['subtotal'] %}
            </tr>
            {% endfor %}
            <tr>
                <td class="text-end" colspan="100%">
                    Total: {{ns.total or 0}}
                </td>
            </tr>
        </tbody>
    </table>
    <form action="{{url_for('shop.confirm_order')}}" method="POST">
        <input type="submit" value="Place Order" class="btn btn-secondary btn-sm" />
    </form>
</div>
{% endblock %}

Project/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category or 'info' }}" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

Project/templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            height:24px; 
            width: 100%;
            background-image: none;
            background-repeat: repeat;
            background-attachment: scroll;
            background-position: 0% 0%;
            position: fixed;
            bottom: 0pt;
            left: 0pt;
        }   
        .footer_contents {
            height:24px;
            width: 1000px;
            margin:auto;
        }
        .header {
            top: 0;
            height: 60px;
            line-height: 60px;
        }
    </style>
    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
</head>

<body>
    <div id="header">
        {% include 'nav.html' %}
        {% include 'flash.html' %}
        <style>
            label {
                text-transform: capitalize;
            }
            .center {
                border: 5px solid;
                display: flex;
                justify-content: center;
            }
        </style>
    </div>
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer" class="footer bg-light text-center">
        <div class="footer_contents bg-light text-center">
            {% block footer %}
            &copy; Copyright 2022.
            {% endblock %}
        </div>
    </div>
</body>

</html>

Project/templates/nav.html
{% from "_dropdown_nav.html" import dropdown_nav %}
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">AP SHOP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('shop.shop_list')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.profile')}}">Profile</a>
                </li>
                <!-- roles nav (requires admin )-->
                {% if current_user.is_authenticated and current_user.has_role("Admin") %}
                {% set roles = [
                ("roles.add", "Add"),
                ("roles.list", "List"),
                ("roles.assign", "Assign")
                ] %}
                {{dropdown_nav("Roles", roles)}}
                {% set admin = [
                    ("admin.item", "Add item"),
                    ("admin.items", "List items"),
                    ("admin.orders", "View Orders")    
                    ] %}
                {{dropdown_nav("Admin", admin)}}
                {% endif %}
                {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('shop.cart')}}">Cart</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('shop.orders')}}">Orders</a>
                 </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>

Project/templates/order.html
{% extends "layout.html" %}
{% block title %}Order - #{{request.args.get("id", "")}}{% endblock %}

<!-- content -->
{% block content %}
{% from "_table_helper.html" import render_table %}
<div class="h2">Order Summary:</div>
<div class="h5">Order Number #{{request.args.get('id')}}:</div>
{{render_table("Address and Billing Details", order_info , [])}}
<br>
<br>
{{render_table("Order", rows, ["user_id"])}}
<div class="text-light lead ms-3">Total Cost: {{total}}</div>
{% endblock %}

Project/templates/order_summary.html
{% extends "layout.html" %}
{% from "_table_helper.html" import render_table %}
{% block title %}Order Confirmation{% endblock %}

<!-- content -->
{% block content %}
<div class="container-fluid">
<div class="h2">Order Summary:</div>
<div class="h3">Order Number #{{order['id']}}:</div>
{{render_table("Address and Billing Details", order_info , [])}}
<br>
<br>
{{render_table("Ordered Items", rows, ["user_id"])}}
<div>Order Total: ${{order['total']}}</div>
<br>
<div class="h4">Thank you for ordering from us! Please wait for 4-5 business days for the package to get delivered. :)</div>
{% endblock %}

Project/templates/orders.html
{% extends "layout.html" %}
{% block title %}Orders{% endblock %}

<!-- content -->
{% block content %}
{% from "_table_helper.html" import render_table %}
{% if current_user.has_role("Admin") %}
{% set view = "admin.order" %}
{% else %}
{% set view = "shop.order" %}
{% endif %}
{{render_table("Orders", rows, ["user_id"], view)}}
{% endblock %}

Project/templates/payment.html
{% extends "layout.html" %}
{% block title %}Payment{% endblock %}

{% block content %}
<div class="container-fluid">
    <form class="form-group mb-3 align-items-center" action="{{url_for('shop.place_order')}}"
            method="POST">
        <div class="col-12 text-center">
            <label for="total">Amount to be paid</label>
            <input type="text" name="total" class="form-control" id="total" placeholder="0" readonly
                value="{{request.form.get('total') or form.get('money_received') or ''}}">
        </div>
        <br>
        <div class="col-12 text-center">
            <label for="money_received">Enter Payment Amount</label>
            <input type="text" name="money_received" class="form-control" id="money_received" placeholder="Enter Amount"
                value="{{request.form.get('money_received') or form.get('money_received') or ''}}">
        </div>
        <div class="col-12 text-center">
            <input type="submit" value="Pay" class="btn btn-danger btn-sm" />
        </div>
        <input type="hidden" name="fname" value="{{request.form.get('fname') or form.get('fname') or ''}}" />
        <input type="hidden" name="lname" value="{{request.form.get('lname') or form.get('lname') or ''}}" />
        <input type="hidden" name="address" value="{{request.form.get('address') or form.get('address') or ''}}" />
        <input type="hidden" name="payment" value="{{request.form.get('payment') or form.get('payment') or ''}}" />
    </form>
</div>
{% endblock %}

Project/templates/sort_filter.html
<div class="col-12">
    <label class="visually-hidden" for="col">Field</label>
    <select class="form-select" id="col" name="column" value="{{request.args.get('column', '')}}">
        <option value="">Field...</option>
        {% for v in cols %}
        <option {{'selected' if v==request.args.get('column', '' )}} value="{{v}}">{{v}}</option>
        {% endfor %}
    </select>
</div>
<div class="col-12">
    <label class="visually-hidden" for="order">Order</label>
    <select class="form-select" id="order" name="order" value="{{request.args.get('order', 'asc')}}">
        <option {{'selected' if request.args.get('order')=='asc' }} value="asc">Up</option>
        <option {{'selected' if request.args.get('order')=='desc' }} value="desc">Down</option>
    </select>
</div>

Project/templates/view_item.html
{% extends "layout.html" %}
{%block content%}
<div class="container">
    <div class="card card-customised p-3 mb-2 bg-dark text-white" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title">{{ rows.get('name') }}</h5>
            <br>
            {% for k,v in rows.items() %}
            {% if k=='image'%}
            <span class="label label-default">{{k}}: <img src="{{v}}" style="aspect-ratio: 1; width:100%"></span>
            {% else %}
            <span class="label label-default">{{k}}: {{v}}</span>
            {% endif %}
            <br>
            <br>
            {% endfor %}
            {% if current_user.is_authenticated and current_user.has_role("Admin") %}
            <form action="{{url_for('admin.item')}}?id={{rows['id']}}" method="POST">
                <input type="submit" value="edit" />
            </form>
            {% endif %}
            
        </div>
    </div>
</div>
{% endblock %}

Project/templates/welcome.html
{% extends "layout.html" %}
{% block content %}
<div class="text-center"> 
<font size="+4" >
Welcome to AP Shop
<br>
Login/Register to start shopping
</div>
</font>
{% endblock %}