BusinessManagement/views/admin.py
import io
import csv
from flask import Blueprint, render_template, request, redirect, flash
from werkzeug.utils import secure_filename
from sql.db import DB
import traceback
admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route("/import", methods=["GET","POST"])
def importCSV():
    # UCID: ap2823
    # Date: 12/04/2022
    # Method to import csv     
    if request.method == "POST":
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file', "warning")
            return redirect(request.url)
        # TODO importcsv-1 check that it's a .csv file, return a proper flash message if it's not
        if file and secure_filename(file.filename):
            if not file.filename.endswith(".csv"):
                flash("Selected file is not a csv file", "danger")
                return redirect(request.url)
            companies = []
            employees = []
            company_query = """
            INSERT INTO IS601_MP2_Companies (name, address, city, country, state, zip, website)
                        VALUES (%(name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(website)s)
                        ON DUPLICATE KEY UPDATE address = %(address)s, city = %(city)s, country=%(country)s, state=%(state)s, zip=%(zip)s, website=%(website)s 
            """
            employee_query = """
             INSERT INTO IS601_MP2_Employees (first_name, last_name, email, company_id)
                        VALUES (%(first_name)s, %(last_name)s, %(email)s, (SELECT id FROM IS601_MP2_Companies WHERE name = %(company_name)s LIMIT 1))
                        ON DUPLICATE KEY UPDATE first_name=%(first_name)s, last_name = %(last_name)s, email = %(email)s, company_id = (SELECT id FROM IS601_MP2_Companies WHERE name = %(company_name)s LIMIT 1)
            """
            # Note: this reads the file as a stream instead of requiring us to save it
            stream = io.TextIOWrapper(file.stream._file, "UTF8", newline=None)
            # TODO importcsv-2 read the csv file stream as a dict
            # UCID: ap2823
            # Date: 12/04/2022
            # Reading csv as dict and processing it
            for row in csv.DictReader(stream, delimiter=','):
                # print(row) #example
                # TODO importcsv-3 extract company data and append to company list as a dict only with company data
                if row["company_name"] and row["address"] and row["city"] and row["state"] and row["zip"] and row["web"] and row["country"]:
                    companies.append({"name": row["company_name"],
                                      "address": row["address"],
                                      "city": row["city"],
                                      "country": row["country"],
                                      "state": row["state"],
                                      "zip": row["zip"],
                                      "website": row["web"]})
                # TODO importcsv-4 extract employee data and append to employee list as a dict only with employee data
                if row["first_name"] and row["last_name"] and row["email"]:
                    employees.append({"first_name": row["first_name"],
                                      "last_name": row["last_name"],
                                      "email": row["email"],
                                      "company_name": row.get("company_name", None)})
               
            if len(companies) > 0:
                print(f"Inserting or updating {len(companies)} companies")
                try:
                    result = DB.insertMany(company_query, companies)
                    # TODO importcsv-5 display flash message about number of companies inserted
                    flash(f"Inserted {len(companies)} companies", "success")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-6 display flash message (info) that no companies were loaded
                flash("No Companies were inserted", "success")
                pass
            if len(employees) > 0:
                print(f"Inserting or updating {len(employees)} employees")
                try:
                    result = DB.insertMany(employee_query, employees)
                    flash(f"Inserted {len(employees)} employees", "success")
                    # TODO importcsv-7 display flash message about number of employees loaded
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                 # TODO importcsv-8 display flash message (info) that no companies were loaded
                flash("No employees were inserted", "success")
                pass
    return render_template("upload.html")

BusinessManagement/views/company.py
import traceback as tb
from flask import Blueprint, render_template, request, flash, redirect, url_for
from sql.db import DB
from views.forms import *
company = Blueprint('company', __name__, url_prefix='/company')

@company.route("/search", methods=["GET"])
def search():
    # UCID: ap2823
    # Date: 12/04/2022
    # Method to search companies using request args
    rows = []
    # DO NOT DELETE PROVIDED COMMENTS
    # TODO search-1 retrieve id, name, address, city, country, state, zip, website, employee count for the company
    # don't do SELECT *
    query = """SELECT id, name, address, city, country, state, zip, website,
               (SELECT count(*) from IS601_MP2_Employees A
                WHERE A.company_id = B.id) AS employees
               FROM IS601_MP2_Companies B
               WHERE 1=1"""
    args = [] # <--- append values to replace %s placeholders
    allowed_columns = ["name", "city", "country", "state"]
    # TODO search-2 get name, country, state, column, order, limit request args
    # TODO search-3 append a LIKE filter for name if provided
    # TODO search-4 append an equality filter for country if provided
    # TODO search-5 append an equality filter for state if provided
    # TODO search-6 append sorting if column and order are provided and within the allows columsn and allowed order asc,desc
    # TODO search-7 append limit (default 10) or limit greater than 1 and less than or equal to 100
    # TODO search-8 provide a proper error message if limit isn't a number or if it's out of bounds
    filters = ["country", "state"]
    if request.args.get("name"):
        query += " and name like %s"
        args.append(f"%{request.args.get('name')}%")
    for filter in filters:
        if request.args.get(filter):
            query += f" and {filter} = %s"
            args.append(request.args.get(filter))
    if request.args.get("order") and request.args.get("column"):
        if request.args.get("column") in allowed_columns \
            and request.args.get("order") in ["asc", "desc"]:
            query += f" ORDER BY {request.args.get('column')} {request.args.get('order')}"
    query += f" LIMIT %s"
    ql = int(request.args.get('limit', 10))
    if ql < 1 or ql > 100:
        flash("limit value should be in the range of 1-100; Defaulting to 10")
        args.append(10)
    else:
        args.append(ql)
    print("query",query)
    print("args", args)
    try:
        result = DB.selectAll(query, *args)
        if result.status:
            rows = result.rows
    except Exception as e:
        # TODO search-9 make message user friendly
        print(tb.format_exc)
        flash(f"Unexpected error while trying to search company: {e}", "danger")
    # hint: use allowed_columns in template to generate sort dropdown
    allowed_columns = [(col,col) for col in allowed_columns]
    print(rows)
    return render_template("list_companies.html", rows=rows, allowed_columns=allowed_columns)

@company.route("/add", methods=["GET","POST"])
def add():
    # UCID: ap2823
    # Date: 12/04/2022
    # Method to add companies using WTForms
    form = Company(request.form)
    if request.method == "POST":
        form_data = {}
        has_error = False
        # if not form.validate_on_submit():
        #     raise 
        # TODO add-1 retrieve form data for name, address, city, state, country, zip, website
        # TODO add-2 name is required (flash proper error message)
        # TODO add-3 address is required (flash proper error message)
        # TODO add-4 city is required (flash proper error message)
        # TODO add-5 state is required (flash proper error message)
        # TODO add-6 country is required (flash proper error message)
        # TODO add-7 website is not required
        form_data["name"] = form.name.data
        form_data["address"] = form.address.data
        form_data["city"] = form.city.data
        form_data["country"] = request.form.get("country")
        form_data["state"] = request.form.get("state")
        form_data["zip_code"] = form.zip.data
        form_data["website"] = form.website.data
        for k,v in form_data.items():
            if k != "website" and not v:
                flash(f"{k} is a mandatory field", "danger")
                has_error = True
        if not has_error:
            try:
                result = DB.insertOne("""
                INSERT INTO IS601_MP2_Companies (name, address, city, country,
                state, zip, website)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """, *form_data.values()
                ) # <-- TODO add-8 add query and add arguments
                if result.status:
                    flash("Added Company", "success")
            except Exception as e:
                # TODO add-9 make message user friendly
                print(tb.format_exc)
                flash(f"Unexpected error while trying to add company: {e}", "danger")
    return render_template("add_company.html", form=form)

@company.route("/edit", methods=["GET", "POST"])
def edit():
    # UCID: ap2823
    # Date: 12/04/2022
    # Method to edit companies using WTForms
    form = Company(request.form)
    # TODO edit-1 request args id is required (flash proper error message)
    if request.args.get('id'): # TODO update this for TODO edit-1
        if request.method == "POST":
            # TODO edit-2 retrieve form data for name, address, city, state, country, zip, website
            # TODO edit-3 name is required (flash proper error message)
            # TODO edit-4 address is required (flash proper error message)
            # TODO edit-5 city is required (flash proper error message)
            # TODO edit-6 state is required (flash proper error message)
            # TODO edit-7 country is required (flash proper error message)
            # TODO edit-8 website is not required
            # 
            # note: call zip variable zipcode as zip is a built in function it could lead to issues
            #data = [name, address, city, state, country, zipcode, website]
            form_data = {}
            has_error = False
            # if not form.validate_on_submit():
            #     return render_template("edit_company.html.html", form=form)
            form_data["name"] = form.name.data
            form_data["address"] = form.address.data
            form_data["city"] = form.city.data
            form_data["country"] = request.form.get("country")
            form_data["state"] = request.form.get("state")
            form_data["zip_code"] = form.zip.data
            form_data["website"] = form.website.data
            form_data["id"] = request.args.get('id')
            for k,v in form_data.items():
                if k != "website" and not v:
                    flash(f"{k} is a mandatory field", "danger")
                    has_error = True
            print("boi",form_data)
            if not has_error:
                try:
                    # TODO edit-9 fill in proper update query
                    result = DB.update("""
                    UPDATE IS601_MP2_Companies 
                    SET name=%s, address=%s, city=%s, country=%s, state=%s,
                    zip=%s, website=%s
                    WHERE id=%s
                    """, *form_data.values())
                    if result.status:
                        flash("Updated record", "success")
                except Exception as e:
                    print(tb.format_exc)
                    print(e)
                    # TODO edit-10 make this user-friendly
                    flash(f"Unexpected error while trying to edit company: {e}", "danger")
        # UCID: ap2823
        # Date: 12/04/2022
        # Fetching the newly updated record
        try:
            # TODO edit-11 fetch the updated data
            result = DB.selectOne("""SELECT * FROM IS601_MP2_Companies
            WHERE id=%s""", request.args.get('id'))
            if result.status:
                row = result.row
                print(row)
                form.name.data = row['name']
                form.address.data = row['address']
                form.city.data = row['city']
                form.zip.data = row['zip']
                form.website.data = row['website']
        except Exception as e:
            print(tb.format_exc())
            print(e)
            # TODO edit-12 make this user-friendly
            flash(f"Unexpected error while trying to fetch the updated company: {e}", "danger")
    else:
        flash("Company ID is missing", "danger")
    # TODO edit-13 pass the company data to the render template
    return render_template("edit_company.html", form=form, country=row.get("country"), state=row.get("state"))

@company.route("/delete", methods=["GET"])
def delete():
    # TODO delete-1 delete company by id (unallocate any employees)
    # TODO delete-2 redirect to company search
    # TODO delete-3 pass all argument except id to this route
    # TODO delete-4 ensure a flash message shows for successful delete
    # UCID: ap2823
    # Date: 12/04/2022
    # Method to delete company using company_id and then redirect to listing page
    # All references are set to NULL before deleting the company
    if request.method == "GET":
        cmp_id = request.args.get("id")
        if not cmp_id:
            flash("Company ID is missing", "danger")
            return render_template("list_companies.html", **request.args)
        try:
            constraint_fix = DB.update("""
            UPDATE IS601_MP2_Employees
            SET company_id = NULL
            WHERE company_id = %s
            """,cmp_id)

            result = DB.delete("""
            DELETE FROM IS601_MP2_Companies
            WHERE id = %s
            """, cmp_id)

            if constraint_fix.status and result.status:
                flash("Deleted Record", "success")
        except Exception as e:
            flash(f"Unexpected error while trying to delete the Company: {e}", "danger")

BusinessManagement/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    status = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        list(pycountry.subdivisions.get(country_code=request.args.get('country_code', 'US')))))
    return json.dumps(status)

BusinessManagement/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

BusinessManagement/templates/_formhelpers.html
{% macro render_field(field) %}
{# demonstrating a macro (basically a template function)
modified from https://flask.palletsprojects.com/en/2.2.x/patterns/wtforms/
#}
<div class="form-group mb-3">
    {{ field.label(class="form-label") }}
    {{ field(class="form-control",**kwargs)|safe }}
    {% if field.errors %}
    <ul class="errors">
        {% for error in field.errors %}
        <li class="text-danger">{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endmacro %}

BusinessManagement/templates/add_company.html
{% extends "layout.html" %}
{% block title %}Add Company{% endblock %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="h1">Add Company</div>
    <div>
        <form method="POST">
            {{form.hidden_tag()}}
            {{render_field(form.name)}}
            {{render_field(form.address)}}
            {{render_field(form.city)}}
            {{render_field(form.zip)}}
            {{render_field(form.website)}}
            {# use this for country/state selection #}
            {% include "country_state_selector.html" %}
            <input type="submit" class="btn btn-primary" value="submit" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/add_employee.html
{% extends "layout.html" %}
{% block title %}Add Employee{% endblock %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="h1">Add Employee</div>
    <div>
        <form method="POST">
            {{form.hidden_tag()}}
            {{render_field(form.first_name)}}
            {{render_field(form.last_name)}}
            {{render_field(form.email)}}
            {# use the below for company selection #}
            {% include "company_dropdown.html" %}
            <input type="submit" class="btn btn-primary" value="submit" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/company_dropdown.html
{% set comps = get_companies() %}
{# can set val prior to inclusion to prefill this field #}
{# TODO DO NOT EDIT #}
<select class="form-select" name="company" value="{{val or ''}}">
    <option value="">No Company</option>
    {% for c in comps %}
    {# example of using external data setting and casting #}
    <option {{'selected' if val|string==c['id']|string}} value="{{c['id']}}">{{c['name']}}</option>
    {% endfor %}
</select>

BusinessManagement/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% set c = request.args.get("country", request.form.get("country", country or '')) %}
{% set s = request.args.get("state", request.form.get("state", state or '')) %}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col-12">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col-12">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{s}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    }
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{c}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>

BusinessManagement/templates/edit_company.html
{% extends "layout.html" %}
{% block title %}Edit Company{% endblock %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="h1">Edit Company</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            name
            address
            city
            website
            and prefill the fields with loaded company data
            #}
            {{form.hidden_tag()}}
            {{render_field(form.name)}}
            {{render_field(form.address)}}
            {{render_field(form.city)}}
            {{render_field(form.zip)}}
            {{render_field(form.website)}}
            {# use this for country/state selection #}
            {% include "country_state_selector.html" %}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category or 'info' }}" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

BusinessManagement/templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            display: block;
        }

        .header {
            top: 0;
            height: 60px;
            line-height: 60px;
        }
    </style>
    <title>{% block title %}{% endblock %} - MP2</title>
    {% endblock %}
</head>

<body>
    <div id="header">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                {# TODO replace my ucid mt85 with your ucid #}
                <a class="navbar-brand" href="{{url_for('home.index')}}">DIAR-ap2823</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {# TODO fill in the relevant hrefs using url_for() #}
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- company dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Company
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('company.search')}}">Search</a></li>
                                <li><a class="dropdown-item" href="{{url_for('company.add')}}">Add</a></li>

                            </ul>
                        </li>
                        <!-- employee dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Employee
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('employee.search')}}">Search</a></li>
                                <li><a class="dropdown-item" href="{{url_for('employee.add')}}">Add</a></li>
                            </ul>
                        </li>
                        <!-- admin dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('admin.importCSV')}}">Import</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% include 'flash.html' %}
    </div>
    <div id="content" class="overflow-scroll" style="height: 84vh">
        {% block content %} {% endblock %}
    </div>
    <div id=" footer" class="footer mt-auto py-3 bg-light text-center fixed-bottom">
        <div class="container">
            {% block footer %}
            <span>Business Management &copy; Copyright 2022.</span>
            {% endblock %}
        </div>
    </div>
</body>

</html>

BusinessManagement/templates/list_companies.html
{% extends "layout.html" %}
{% block title %}Company Directory{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center">Company Directory</div>
    {# TODO
    build a horizontal filter/sort form with
    name (company name)
    country/state (provided)
    sort/order (using allowed_columns and provided partial template)
    limit
    ensure all fields prefill with request arg data if provided
    #}
    <form class="row row-cols-lg-auto g-3 align-items-center" method="GET">
        <div class="col-12">
            <label class="visually-hidden" for="name">Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Name"
                value="{{request.args.get('name') or ''}}">
        </div>
        {% with layout = "horizontal" %}
        {% include "country_state_selector.html" %}
        {% endwith %}
        {% with cols = allowed_columns %}
        {% include "sort_filter.html" %}
        {% endwith %}
        <div class="col-12">
            <label class="visually-hidden for="limit">Limit</label>
            <input class="form-control" type="number" min="1" max="100" id="limit" name="limit"
                value="{{request.args.get('limit') or '10'}}" />
        </div>
        <div class="col-12">
            <input type="submit" class="btn btn-primary" value="Filter" />
        </div>
        <div class="col-12">
            <a href="?" class="btn btn-secondary">Reset</a>
        </div>
    </form>
    <div class="table-responsive">
    <table class="table">
        {% if rows and rows|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {# generate th tags for each column to display #}
                {# IMPORTANT use table column names as the headings, replace _ with space #}
                {% for r in rows[0] %}
                <th>{{r | replace('_', ' ')}}</th>
                {% endfor %}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {# generate tr with td tags for each piece of data #}
            {# if the td is for website, display it as a link where the text is "website" and the url is the
            website url #}
            {# in the last column add the following
            a view button that passes the company id to employee search (this will be a company employee
            directory) also pass company_name as an argument
            an edit button that passes the company id to company edit
            a delete button that passes the company id and the request args to the company delete route
            #}
            {% for r in rows %}
            <tr>   
                {% for k,v in r.items() %}
                    {% if k == "website" %}
                        <td>
                            <a href="{{v}}" class="btn btn-secondary btn-sm">website</a>
                        </td>
                    {% else %}
                        <td>{{v}}</td>
                    {% endif %}
                {% endfor %}
                <td>
                    <a href="{{url_for('employee.search', company=r.get('id'))}}" class="btn btn-secondary btn-sm">View</a>
                    <a href="{{url_for('company.edit', id=r.get('id'))}}" class="btn btn-secondary btn-sm">Edit</a>
                    <a href="{{url_for('company.delete', id=r.get('id'), **request.args)}}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr> 
            {% endfor %} 
        </tbody>
        {% else %}
        <tbody>
            <tr>
                <td colspan="100%">No results to show</td>
            </tr>
        </tbody>
        {% endif %}
    </table>
    </div>
</div>
{% endblock %}